### ISSUE TITLE
Inefficient CSS

### ISSUE THREAD

**Issue by AbleLincoln** [zoobereq/prj-rev-bwfs-dasmoto#5]
You see how you have written the same font-family, font-size, font-weight, and color three separate times? This is inefficient CSS. The best part of CSS is that when written effectively you can drastically reduce the amount of code. CSS has the amazing ability to select and style multiple elements at once. You're not taking advantage of that here, resulting in redundant code. Here is an example of how you could clean this up:
```css
.brushes, .frames, .paint {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

(You could even get rid of the font-family since you've already styled that on line 2 of your CSS).

https://github.com/zoobereq/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/Resources/css/style.css#L14-L36
